-- ============================================================
-- Seed NSE Large Cap Stocks (NIFTY 50 universe sample)
-- Run AFTER schema.sql
-- ============================================================
insert into public.stocks (symbol, name, exchange, sector, cap_category, market_cap) values
  ('RELIANCE',   'Reliance Industries Ltd',        'NSE', 'Energy',               'Large Cap', 1950000000000),
  ('TCS',        'Tata Consultancy Services Ltd',  'NSE', 'Information Technology','Large Cap', 1400000000000),
  ('HDFCBANK',   'HDFC Bank Ltd',                  'NSE', 'Financial Services',   'Large Cap', 1200000000000),
  ('ICICIBANK',  'ICICI Bank Ltd',                 'NSE', 'Financial Services',   'Large Cap',  800000000000),
  ('BHARTIARTL', 'Bharti Airtel Ltd',              'NSE', 'Telecommunication',    'Large Cap',  750000000000),
  ('INFY',       'Infosys Ltd',                    'NSE', 'Information Technology','Large Cap',  650000000000),
  ('SBIN',       'State Bank of India',            'NSE', 'Financial Services',   'Large Cap',  600000000000),
  ('HINDUNILVR', 'Hindustan Unilever Ltd',         'NSE', 'FMCG',                 'Large Cap',  550000000000),
  ('ITC',        'ITC Ltd',                        'NSE', 'FMCG',                 'Large Cap',  520000000000),
  ('LT',         'Larsen & Toubro Ltd',            'NSE', 'Construction',         'Large Cap',  500000000000),
  ('KOTAKBANK',  'Kotak Mahindra Bank Ltd',        'NSE', 'Financial Services',   'Large Cap',  390000000000),
  ('AXISBANK',   'Axis Bank Ltd',                  'NSE', 'Financial Services',   'Large Cap',  370000000000),
  ('BAJFINANCE', 'Bajaj Finance Ltd',              'NSE', 'Financial Services',   'Large Cap',  430000000000),
  ('ASIANPAINT', 'Asian Paints Ltd',               'NSE', 'Consumer Durables',    'Large Cap',  260000000000),
  ('MARUTI',     'Maruti Suzuki India Ltd',        'NSE', 'Automobile',           'Large Cap',  340000000000),
  ('TITAN',      'Titan Company Ltd',              'NSE', 'Consumer Durables',    'Large Cap',  290000000000),
  ('WIPRO',      'Wipro Ltd',                      'NSE', 'Information Technology','Large Cap',  280000000000),
  ('HCLTECH',    'HCL Technologies Ltd',           'NSE', 'Information Technology','Large Cap',  380000000000),
  ('SUNPHARMA',  'Sun Pharmaceutical Industries', 'NSE', 'Healthcare',            'Large Cap',  300000000000),
  ('TATAMOTORS', 'Tata Motors Ltd',               'NSE', 'Automobile',            'Large Cap',  310000000000),
  ('ULTRACEMCO', 'UltraTech Cement Ltd',          'NSE', 'Construction Materials','Large Cap',  250000000000),
  ('NESTLEIND',  'Nestle India Ltd',              'NSE', 'FMCG',                  'Large Cap',  200000000000),
  ('POWERGRID',  'Power Grid Corporation of India','NSE','Power',                 'Large Cap',  210000000000),
  ('NTPC',       'NTPC Ltd',                      'NSE', 'Power',                 'Large Cap',  300000000000),
  ('ONGC',       'Oil & Natural Gas Corporation', 'NSE', 'Oil & Gas',             'Large Cap',  340000000000),
  ('COALINDIA',  'Coal India Ltd',                'NSE', 'Metals & Mining',       'Large Cap',  220000000000),
  ('ADANIPORTS', 'Adani Ports & SEZ Ltd',         'NSE', 'Services',              'Large Cap',  250000000000),
  ('BAJAJFINSV', 'Bajaj Finserv Ltd',             'NSE', 'Financial Services',    'Large Cap',  270000000000),
  ('DRREDDY',    'Dr. Reddy Laboratories Ltd',    'NSE', 'Healthcare',            'Large Cap',  120000000000),
  ('CIPLA',      'Cipla Ltd',                     'NSE', 'Healthcare',            'Large Cap',  100000000000),
  ('TECHM',      'Tech Mahindra Ltd',             'NSE', 'Information Technology','Large Cap',  130000000000),
  ('HINDALCO',   'Hindalco Industries Ltd',       'NSE', 'Metals & Mining',       'Large Cap',  140000000000),
  ('JSWSTEEL',   'JSW Steel Ltd',                 'NSE', 'Metals & Mining',       'Large Cap',  160000000000),
  ('TATASTEEL',  'Tata Steel Ltd',                'NSE', 'Metals & Mining',       'Large Cap',  150000000000),
  ('GRASIM',     'Grasim Industries Ltd',         'NSE', 'Construction Materials','Large Cap',  140000000000),
  ('DIVISLAB',   'Divi Laboratories Ltd',         'NSE', 'Healthcare',            'Large Cap',   95000000000),
  ('BRITANNIA',  'Britannia Industries Ltd',      'NSE', 'FMCG',                  'Large Cap',  115000000000),
  ('EICHERMOT',  'Eicher Motors Ltd',             'NSE', 'Automobile',            'Large Cap',  120000000000),
  ('INDUSINDBK', 'IndusInd Bank Ltd',             'NSE', 'Financial Services',    'Large Cap',  110000000000),
  ('HEROMOTOCO', 'Hero MotoCorp Ltd',             'NSE', 'Automobile',            'Large Cap',   90000000000),
  ('BPCL',       'Bharat Petroleum Corporation', 'NSE', 'Oil & Gas',              'Large Cap',  120000000000),
  ('IOC',        'Indian Oil Corporation Ltd',   'NSE', 'Oil & Gas',              'Large Cap',  160000000000),
  ('APOLLOHOSP', 'Apollo Hospitals Enterprise', 'NSE', 'Healthcare',              'Large Cap',  100000000000),
  ('BAJAJ-AUTO', 'Bajaj Auto Ltd',               'NSE', 'Automobile',             'Large Cap',  200000000000),
  ('TATACONSUM', 'Tata Consumer Products Ltd',  'NSE', 'FMCG',                    'Large Cap',   90000000000),
  ('SBILIFE',    'SBI Life Insurance Company', 'NSE', 'Financial Services',        'Large Cap',  140000000000),
  ('HDFCLIFE',   'HDFC Life Insurance Company','NSE', 'Financial Services',        'Large Cap',  130000000000),
  ('ICICIPRULI', 'ICICI Prudential Life Insurance','NSE','Financial Services',     'Large Cap',   90000000000),
  ('M&M',        'Mahindra and Mahindra Ltd',  'NSE', 'Automobile',               'Large Cap',  250000000000),
  ('ADANIENT',   'Adani Enterprises Ltd',      'NSE', 'Conglomerate',             'Large Cap',  200000000000)
on conflict (symbol) do update set
  name = excluded.name,
  sector = excluded.sector,
  cap_category = excluded.cap_category,
  market_cap = excluded.market_cap,
  updated_at = now();

-- Mid Cap additions
insert into public.stocks (symbol, name, exchange, sector, cap_category) values
  ('PIDILITIND',  'Pidilite Industries Ltd',     'NSE', 'Chemicals',             'Mid Cap'),
  ('HAVELLS',     'Havells India Ltd',           'NSE', 'Consumer Durables',     'Mid Cap'),
  ('VOLTAS',      'Voltas Ltd',                  'NSE', 'Consumer Durables',     'Mid Cap'),
  ('MUTHOOTFIN',  'Muthoot Finance Ltd',         'NSE', 'Financial Services',    'Mid Cap'),
  ('CHOLAFIN',    'Cholamandalam Investment',    'NSE', 'Financial Services',    'Mid Cap'),
  ('PERSISTENT',  'Persistent Systems Ltd',      'NSE', 'Information Technology','Mid Cap'),
  ('COFORGE',     'Coforge Ltd',                 'NSE', 'Information Technology','Mid Cap'),
  ('LTIM',        'LTIMindtree Ltd',             'NSE', 'Information Technology','Large Cap'),
  ('MPHASIS',     'Mphasis Ltd',                 'NSE', 'Information Technology','Mid Cap'),
  ('PAGEIND',     'Page Industries Ltd',         'NSE', 'Textiles',              'Mid Cap'),
  ('ASTRAL',      'Astral Ltd',                  'NSE', 'Construction Materials','Mid Cap'),
  ('POLYCAB',     'Polycab India Ltd',           'NSE', 'Consumer Durables',     'Mid Cap'),
  ('CAMS',        'CAMS (Computer Age Mgmt)',    'NSE', 'Financial Services',    'Mid Cap'),
  ('METROPOLIS',  'Metropolis Healthcare Ltd',   'NSE', 'Healthcare',            'Mid Cap'),
  ('LALPATHLAB',  'Dr. Lal PathLabs Ltd',        'NSE', 'Healthcare',            'Mid Cap')
on conflict (symbol) do update set
  name = excluded.name,
  sector = excluded.sector,
  cap_category = excluded.cap_category,
  updated_at = now();

select count(*) as stocks_seeded from public.stocks;
